from __future__ import annotations

from domain.models import CtSeries, DxSeries, ImagingStudy, MgSeries, MrSeries, UsSeries, WsiSeries


class RadiologyBuilder:
    def build_imaging_study(self, payload: dict) -> ImagingStudy:
        return ImagingStudy(
            accession_number=str(payload["accession_number"]),
            source_id=str(payload.get("source_id", payload.get("id", payload["accession_number"]))),
            imaging_study_identifier=payload.get("imaging_study_identifier"),
            belongs_to_person=payload.get("belongs_to_person"),
            imaging_modalities=payload.get("imaging_modalities"),
            body_regions=payload.get("body_regions"),
            imaging_procedures=payload.get("imaging_procedures"),
            reason_for_imaging_procedure=payload.get("reason_for_imaging_procedure"),
            study_start_date=payload.get("study_start_date"),
            dicom_series_count=payload.get("dicom_series_count"),
            dicom_images_count=payload.get("dicom_images_count"),
            affiliated_institution=payload.get("affiliated_institution"),
            ct_series=[self._build_ct_series(item) for item in payload.get("ct_series", [])],
            mr_series=[self._build_mr_series(item) for item in payload.get("mr_series", [])],
            us_series=[self._build_us_series(item) for item in payload.get("us_series", [])],
            dx_series=[self._build_dx_series(item) for item in payload.get("dx_series", [])],
            mg_series=[self._build_mg_series(item) for item in payload.get("mg_series", [])],
            wsi_series=[self._build_wsi_series(item) for item in payload.get("wsi_series", [])],
        )

    def _build_ct_series(self, payload: dict) -> CtSeries:
        return CtSeries(
            source_id=str(payload.get("source_id", payload.get("id", "unknown"))),
            series_identifier=payload.get("series_identifier"),
            imaging_study_identifier=payload.get("imaging_study_identifier"),
            dicom_images_count=payload.get("dicom_images_count"),
            series_start_date=payload.get("series_start_date"),
            body_region=payload.get("body_region"),
            laterality=payload.get("laterality"),
            imaging_device=payload.get("imaging_device"),
            manufacturer_of_imaging_device=payload.get("manufacturer_of_imaging_device"),
            software_version=payload.get("software_version"),
            color_space=payload.get("color_space"),
            pixel_spacing=payload.get("pixel_spacing"),
            image_type=payload.get("image_type"),
            file_format=payload.get("file_format"),
            file_size=payload.get("file_size"),
            image_width=payload.get("image_width"),
            image_height=payload.get("image_height"),
            image_depth=payload.get("image_depth"),
            number_of_channels=payload.get("number_of_channels"),
            channel_resolution=payload.get("channel_resolution"),
            compression_method=payload.get("compression_method"),
            compression_quality_label=payload.get("compression_quality_label"),
            annotations_available=payload.get("annotations_available"),
            tube_voltage_kvp=payload.get("tube_voltage_kvp"),
            x_ray_tube_current_ma=payload.get("x_ray_tube_current_ma"),
            exposure_time_ms=payload.get("exposure_time_ms"),
            spiral_pitch_factor=payload.get("spiral_pitch_factor"),
            filter_type=payload.get("filter_type"),
            convolution_kernel=payload.get("convolution_kernel"),
            field_of_view=payload.get("field_of_view"),
            slice_thickness=payload.get("slice_thickness"),
            imaging_injection=payload.get("imaging_injection"),
            number_of_image_planes=payload.get("number_of_image_planes"),
        )

    def _build_mr_series(self, payload: dict) -> MrSeries:
        return MrSeries(
            source_id=str(payload.get("source_id", payload.get("id", "unknown"))),
            series_identifier=payload.get("series_identifier"),
            imaging_study_identifier=payload.get("imaging_study_identifier"),
            dicom_images_count=payload.get("dicom_images_count"),
            series_start_date=payload.get("series_start_date"),
            body_region=payload.get("body_region"),
            laterality=payload.get("laterality"),
            imaging_device=payload.get("imaging_device"),
            manufacturer_of_imaging_device=payload.get("manufacturer_of_imaging_device"),
            software_version=payload.get("software_version"),
            color_space=payload.get("color_space"),
            pixel_spacing=payload.get("pixel_spacing"),
            image_type=payload.get("image_type"),
            file_format=payload.get("file_format"),
            file_size=payload.get("file_size"),
            image_width=payload.get("image_width"),
            image_height=payload.get("image_height"),
            image_depth=payload.get("image_depth"),
            number_of_channels=payload.get("number_of_channels"),
            channel_resolution=payload.get("channel_resolution"),
            compression_method=payload.get("compression_method"),
            compression_quality_label=payload.get("compression_quality_label"),
            annotations_available=payload.get("annotations_available"),
            sequence_name=payload.get("sequence_name"),
            magnetic_field_strength=payload.get("magnetic_field_strength"),
            mr_acquisition_type=payload.get("mr_acquisition_type"),
            repetition_time=payload.get("repetition_time"),
            echo_time=payload.get("echo_time"),
            imaging_frequency=payload.get("imaging_frequency"),
            flip_angle=payload.get("flip_angle"),
            inversion_time=payload.get("inversion_time"),
            receive_coil_name=payload.get("receive_coil_name"),
            field_of_view=payload.get("field_of_view"),
            slice_thickness=payload.get("slice_thickness"),
            imaging_injection=payload.get("imaging_injection"),
            number_of_image_planes=payload.get("number_of_image_planes"),
        )

    def _build_us_series(self, payload: dict) -> UsSeries:
        return UsSeries(
            source_id=str(payload.get("source_id", payload.get("id", "unknown"))),
            series_identifier=payload.get("series_identifier"),
            imaging_study_identifier=payload.get("imaging_study_identifier"),
            dicom_images_count=payload.get("dicom_images_count"),
            series_start_date=payload.get("series_start_date"),
            body_region=payload.get("body_region"),
            laterality=payload.get("laterality"),
            imaging_device=payload.get("imaging_device"),
            manufacturer_of_imaging_device=payload.get("manufacturer_of_imaging_device"),
            software_version=payload.get("software_version"),
            color_space=payload.get("color_space"),
            pixel_spacing=payload.get("pixel_spacing"),
            image_type=payload.get("image_type"),
            file_format=payload.get("file_format"),
            file_size=payload.get("file_size"),
            image_width=payload.get("image_width"),
            image_height=payload.get("image_height"),
            image_depth=payload.get("image_depth"),
            number_of_channels=payload.get("number_of_channels"),
            channel_resolution=payload.get("channel_resolution"),
            compression_method=payload.get("compression_method"),
            compression_quality_label=payload.get("compression_quality_label"),
            annotations_available=payload.get("annotations_available"),
            transducer_frequency_mhz=payload.get("transducer_frequency_mhz"),
            mechanical_index=payload.get("mechanical_index"),
            thermal_index=payload.get("thermal_index"),
        )

    def _build_dx_series(self, payload: dict) -> DxSeries:
        return DxSeries(
            source_id=str(payload.get("source_id", payload.get("id", "unknown"))),
            series_identifier=payload.get("series_identifier"),
            imaging_study_identifier=payload.get("imaging_study_identifier"),
            dicom_images_count=payload.get("dicom_images_count"),
            series_start_date=payload.get("series_start_date"),
            body_region=payload.get("body_region"),
            laterality=payload.get("laterality"),
            imaging_device=payload.get("imaging_device"),
            manufacturer_of_imaging_device=payload.get("manufacturer_of_imaging_device"),
            software_version=payload.get("software_version"),
            color_space=payload.get("color_space"),
            pixel_spacing=payload.get("pixel_spacing"),
            image_type=payload.get("image_type"),
            file_format=payload.get("file_format"),
            file_size=payload.get("file_size"),
            image_width=payload.get("image_width"),
            image_height=payload.get("image_height"),
            image_depth=payload.get("image_depth"),
            number_of_channels=payload.get("number_of_channels"),
            channel_resolution=payload.get("channel_resolution"),
            compression_method=payload.get("compression_method"),
            compression_quality_label=payload.get("compression_quality_label"),
            annotations_available=payload.get("annotations_available"),
            patient_orientation=payload.get("patient_orientation"),
            tube_voltage_kvp=payload.get("tube_voltage_kvp"),
            exposure_time_ms=payload.get("exposure_time_ms"),
            exposure_mas=payload.get("exposure_mas"),
        )

    def _build_mg_series(self, payload: dict) -> MgSeries:
        return MgSeries(
            source_id=str(payload.get("source_id", payload.get("id", "unknown"))),
            series_identifier=payload.get("series_identifier"),
            imaging_study_identifier=payload.get("imaging_study_identifier"),
            dicom_images_count=payload.get("dicom_images_count"),
            series_start_date=payload.get("series_start_date"),
            body_region=payload.get("body_region"),
            laterality=payload.get("laterality"),
            imaging_device=payload.get("imaging_device"),
            manufacturer_of_imaging_device=payload.get("manufacturer_of_imaging_device"),
            software_version=payload.get("software_version"),
            color_space=payload.get("color_space"),
            pixel_spacing=payload.get("pixel_spacing"),
            image_type=payload.get("image_type"),
            file_format=payload.get("file_format"),
            file_size=payload.get("file_size"),
            image_width=payload.get("image_width"),
            image_height=payload.get("image_height"),
            image_depth=payload.get("image_depth"),
            number_of_channels=payload.get("number_of_channels"),
            channel_resolution=payload.get("channel_resolution"),
            compression_method=payload.get("compression_method"),
            compression_quality_label=payload.get("compression_quality_label"),
            annotations_available=payload.get("annotations_available"),
            tube_voltage_kvp=payload.get("tube_voltage_kvp"),
            exposure_time_ms=payload.get("exposure_time_ms"),
            exposure_mas=payload.get("exposure_mas"),
            compression_force_n=payload.get("compression_force_n"),
        )

    def _build_wsi_series(self, payload: dict) -> WsiSeries:
        return WsiSeries(
            source_id=str(payload.get("source_id", payload.get("id", "unknown"))),
            series_identifier=payload.get("series_identifier"),
            imaging_study_identifier=payload.get("imaging_study_identifier"),
            dicom_images_count=payload.get("dicom_images_count"),
            series_start_date=payload.get("series_start_date"),
            body_region=payload.get("body_region"),
            laterality=payload.get("laterality"),
            imaging_device=payload.get("imaging_device"),
            manufacturer_of_imaging_device=payload.get("manufacturer_of_imaging_device"),
            software_version=payload.get("software_version"),
            color_space=payload.get("color_space"),
            pixel_spacing=payload.get("pixel_spacing"),
            image_type=payload.get("image_type"),
            file_format=payload.get("file_format"),
            file_size=payload.get("file_size"),
            image_width=payload.get("image_width"),
            image_height=payload.get("image_height"),
            image_depth=payload.get("image_depth"),
            number_of_channels=payload.get("number_of_channels"),
            channel_resolution=payload.get("channel_resolution"),
            compression_method=payload.get("compression_method"),
            compression_quality_label=payload.get("compression_quality_label"),
            annotations_available=payload.get("annotations_available"),
            z_stacking=payload.get("z_stacking"),
            objective_lens_magnification=payload.get("objective_lens_magnification"),
            illumination_method=payload.get("illumination_method"),
            illumination_wavelength=payload.get("illumination_wavelength"),
            scanning_operation_mode=payload.get("scanning_operation_mode"),
            tissue_scan_area=payload.get("tissue_scan_area"),
            number_of_focal_planes=payload.get("number_of_focal_planes"),
            distance_between_focal_planes=payload.get("distance_between_focal_planes"),
            pyramid_levels=payload.get("pyramid_levels"),
            colour_icc_profile=payload.get("colour_icc_profile"),
            preview_available=payload.get("preview_available"),
            label_available=payload.get("label_available"),
            source_assay=payload.get("source_assay"),
        )
