"""init schema

Revision ID: 5f0c3103a18d
Revises:
Create Date: 2026-04-22 17:43:43.435976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f0c3103a18d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "predictive_number_state",
        sa.Column("pseudo_pred_number", sa.String(), nullable=False),
        sa.Column("real_pred_number", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SOURCE_NOT_FOUND",
                "READY_FOR_UPLOAD",
                "UPLOADED",
                "UPLOAD_FAILED",
                name="predictivenumberstatusdb",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column("runs", sa.JSON(), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("pseudo_pred_number"),
    )
    op.create_index(
        op.f("ix_predictive_number_state_status"),
        "predictive_number_state",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_predictive_number_state_status"), table_name="predictive_number_state"
    )
    op.drop_table("predictive_number_state")
    # ### end Alembic commands ###
